
pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/SRCEM-AIM-Class-A/A14_AnshulParate_Djangosub.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t anshulnp/studentproject .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
                    sh 'docker push anshulnp/studentproject'
                }
            }
        }
    }
}
